//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class BrandDto
    {
        
        //Default Constructor
        public BrandDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<BrandDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.BrandId).NotNull();
                RuleFor(x => x.BrandName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.BrandTag).MaximumLength(50).NotEmpty();
                RuleFor(x => x.BrandDescription).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts Brand Dto to Brand EF Model
        /// </summary>
        /// <returns>Brand EF model</returns>
        public Brand ToEFModel()
        {
            var model = new Brand();
            model.BrandId = this.BrandId;
            model.BrandName = this.BrandName;
            model.BrandTag = this.BrandTag;
            model.BrandDescription = this.BrandDescription;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a Brand Entity Model
        /// </summary>
        /// <param name="model">Brand model</param>
        /// <returns>Brand Dto</returns>
        public static BrandDto FromEFModel(Brand model)
        {
            if(model == null) return null;
            var dto = new BrandDto();
            dto.BrandId = model.BrandId;
            dto.BrandName = model.BrandName;
            dto.BrandTag = model.BrandTag;
            dto.BrandDescription = model.BrandDescription;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string BrandTag { get; set; }
        public string BrandDescription { get; set; }
        public int Deleted { get; set; }
    }
}
