//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class ExpensDto
    {
        
        //Default Constructor
        public ExpensDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<ExpensDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.ExpenseId).NotNull();
                RuleFor(x => x.ExpenseTypeId).NotNull();
                RuleFor(x => x.Amount).NotNull();
                RuleFor(x => x.AddedBy).NotNull();
                RuleFor(x => x.PaymentTypeId).NotNull();
                RuleFor(x => x.ExpenseDate).NotNull();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts Expens Dto to Expens EF Model
        /// </summary>
        /// <returns>Expens EF model</returns>
        public Expens ToEFModel()
        {
            var model = new Expens();
            model.ExpenseId = this.ExpenseId;
            model.ExpenseTypeId = this.ExpenseTypeId;
            model.Amount = this.Amount;
            model.AddedBy = this.AddedBy;
            model.PaymentTypeId = this.PaymentTypeId;
            model.ExpenseDate = this.ExpenseDate;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a Expens Entity Model
        /// </summary>
        /// <param name="model">Expens model</param>
        /// <returns>Expens Dto</returns>
        public static ExpensDto FromEFModel(Expens model)
        {
            if(model == null) return null;
            var dto = new ExpensDto();
            dto.ExpenseId = model.ExpenseId;
            dto.ExpenseTypeId = model.ExpenseTypeId;
            dto.Amount = model.Amount;
            dto.AddedBy = model.AddedBy;
            dto.PaymentTypeId = model.PaymentTypeId;
            dto.ExpenseDate = model.ExpenseDate;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int ExpenseId { get; set; }
        public int ExpenseTypeId { get; set; }
        public double Amount { get; set; }
        public int AddedBy { get; set; }
        public int PaymentTypeId { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public int Deleted { get; set; }
    }
}
