//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class ExpenseTypeDto
    {
        
        //Default Constructor
        public ExpenseTypeDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<ExpenseTypeDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.ExpenseTypeId).NotNull();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts ExpenseType Dto to ExpenseType EF Model
        /// </summary>
        /// <returns>ExpenseType EF model</returns>
        public ExpenseType ToEFModel()
        {
            var model = new ExpenseType();
            model.ExpenseTypeId = this.ExpenseTypeId;
            model.ExpenseTypeName = this.ExpenseTypeName;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a ExpenseType Entity Model
        /// </summary>
        /// <param name="model">ExpenseType model</param>
        /// <returns>ExpenseType Dto</returns>
        public static ExpenseTypeDto FromEFModel(ExpenseType model)
        {
            if(model == null) return null;
            var dto = new ExpenseTypeDto();
            dto.ExpenseTypeId = model.ExpenseTypeId;
            dto.ExpenseTypeName = model.ExpenseTypeName;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int ExpenseTypeId { get; set; }
        public string ExpenseTypeName { get; set; }
        public int Deleted { get; set; }
    }
}
