//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class IncomeDto
    {
        
        //Default Constructor
        public IncomeDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<IncomeDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.IncomeId).NotNull();
                RuleFor(x => x.IncomeTypeId).NotNull();
                RuleFor(x => x.Amount).NotNull();
                RuleFor(x => x.AddedBy).NotNull();
                RuleFor(x => x.PaymentTypeId).NotNull();
                RuleFor(x => x.IncomeDate).NotNull();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts Income Dto to Income EF Model
        /// </summary>
        /// <returns>Income EF model</returns>
        public Income ToEFModel()
        {
            var model = new Income();
            model.IncomeId = this.IncomeId;
            model.IncomeTypeId = this.IncomeTypeId;
            model.Amount = this.Amount;
            model.AddedBy = this.AddedBy;
            model.PaymentTypeId = this.PaymentTypeId;
            model.IncomeDate = this.IncomeDate;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a Income Entity Model
        /// </summary>
        /// <param name="model">Income model</param>
        /// <returns>Income Dto</returns>
        public static IncomeDto FromEFModel(Income model)
        {
            if(model == null) return null;
            var dto = new IncomeDto();
            dto.IncomeId = model.IncomeId;
            dto.IncomeTypeId = model.IncomeTypeId;
            dto.Amount = model.Amount;
            dto.AddedBy = model.AddedBy;
            dto.PaymentTypeId = model.PaymentTypeId;
            dto.IncomeDate = model.IncomeDate;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int IncomeId { get; set; }
        public int IncomeTypeId { get; set; }
        public decimal Amount { get; set; }
        public int AddedBy { get; set; }
        public int PaymentTypeId { get; set; }
        public System.DateTime IncomeDate { get; set; }
        public int Deleted { get; set; }
    }
}
