//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int IncomeId { get; set; }
        public int IncomeTypeId { get; set; }
        public decimal Amount { get; set; }
        public int AddedBy { get; set; }
        public int PaymentTypeId { get; set; }
        public System.DateTime IncomeDate { get; set; }
        public int Deleted { get; set; }
    
        public virtual IncomeType IncomeType { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual User User { get; set; }
    }
}
