//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class IncomeTypeDto
    {
        
        //Default Constructor
        public IncomeTypeDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<IncomeTypeDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.IncomeTypeId).NotNull();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts IncomeType Dto to IncomeType EF Model
        /// </summary>
        /// <returns>IncomeType EF model</returns>
        public IncomeType ToEFModel()
        {
            var model = new IncomeType();
            model.IncomeTypeId = this.IncomeTypeId;
            model.IncomeTypeName = this.IncomeTypeName;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a IncomeType Entity Model
        /// </summary>
        /// <param name="model">IncomeType model</param>
        /// <returns>IncomeType Dto</returns>
        public static IncomeTypeDto FromEFModel(IncomeType model)
        {
            if(model == null) return null;
            var dto = new IncomeTypeDto();
            dto.IncomeTypeId = model.IncomeTypeId;
            dto.IncomeTypeName = model.IncomeTypeName;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int IncomeTypeId { get; set; }
        public string IncomeTypeName { get; set; }
        public int Deleted { get; set; }
    }
}
