//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class ProductQuantityDto
    {
        
        //Default Constructor
        public ProductQuantityDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<ProductQuantityDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.ProductId).NotNull();
                RuleFor(x => x.ShopId).NotNull();
                RuleFor(x => x.ShopQty).NotNull();
                RuleFor(x => x.StoresQty).NotNull();
                RuleFor(x => x.KitchenQty).NotNull();
                RuleFor(x => x.Id).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts ProductQuantity Dto to ProductQuantity EF Model
        /// </summary>
        /// <returns>ProductQuantity EF model</returns>
        public ProductQuantity ToEFModel()
        {
            var model = new ProductQuantity();
            model.ProductId = this.ProductId;
            model.ShopId = this.ShopId;
            model.ShopQty = this.ShopQty;
            model.StoresQty = this.StoresQty;
            model.KitchenQty = this.KitchenQty;
            model.Id = this.Id;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a ProductQuantity Entity Model
        /// </summary>
        /// <param name="model">ProductQuantity model</param>
        /// <returns>ProductQuantity Dto</returns>
        public static ProductQuantityDto FromEFModel(ProductQuantity model)
        {
            if(model == null) return null;
            var dto = new ProductQuantityDto();
            dto.ProductId = model.ProductId;
            dto.ShopId = model.ShopId;
            dto.ShopQty = model.ShopQty;
            dto.StoresQty = model.StoresQty;
            dto.KitchenQty = model.KitchenQty;
            dto.Id = model.Id;
            return dto;
        }
    
    
        public int ProductId { get; set; }
        public int ShopId { get; set; }
        public double ShopQty { get; set; }
        public double StoresQty { get; set; }
        public double KitchenQty { get; set; }
        public int Id { get; set; }
    }
}
