//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int UnitId { get; set; }
        public string BarCode { get; set; }
        public int CategoryId { get; set; }
        public int ReOrderLevel { get; set; }
        public double CostPrice { get; set; }
        public double SellingPrice { get; set; }
        public int Deleted { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
