//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class RoleDto
    {
        
        //Default Constructor
        public RoleDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<RoleDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.RoleId).NotNull();
                RuleFor(x => x.RoleName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts Role Dto to Role EF Model
        /// </summary>
        /// <returns>Role EF model</returns>
        public Role ToEFModel()
        {
            var model = new Role();
            model.RoleId = this.RoleId;
            model.RoleName = this.RoleName;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a Role Entity Model
        /// </summary>
        /// <param name="model">Role model</param>
        /// <returns>Role Dto</returns>
        public static RoleDto FromEFModel(Role model)
        {
            if(model == null) return null;
            var dto = new RoleDto();
            dto.RoleId = model.RoleId;
            dto.RoleName = model.RoleName;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public int Deleted { get; set; }
    }
}
