//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class SaleTypeDto
    {
        
        //Default Constructor
        public SaleTypeDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<SaleTypeDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.SaleTypeId).NotNull();
                RuleFor(x => x.SaleTypeName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.SaleTypeStatus).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts SaleType Dto to SaleType EF Model
        /// </summary>
        /// <returns>SaleType EF model</returns>
        public SaleType ToEFModel()
        {
            var model = new SaleType();
            model.SaleTypeId = this.SaleTypeId;
            model.SaleTypeName = this.SaleTypeName;
            model.SaleTypeStatus = this.SaleTypeStatus;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a SaleType Entity Model
        /// </summary>
        /// <param name="model">SaleType model</param>
        /// <returns>SaleType Dto</returns>
        public static SaleTypeDto FromEFModel(SaleType model)
        {
            if(model == null) return null;
            var dto = new SaleTypeDto();
            dto.SaleTypeId = model.SaleTypeId;
            dto.SaleTypeName = model.SaleTypeName;
            dto.SaleTypeStatus = model.SaleTypeStatus;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int SaleTypeId { get; set; }
        public string SaleTypeName { get; set; }
        public string SaleTypeStatus { get; set; }
        public int Deleted { get; set; }
    }
}
