//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class SaleDto
    {
        
        //Default Constructor
        public SaleDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<SaleDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.SaleId).NotNull();
                RuleFor(x => x.TotalTendered).NotNull();
                RuleFor(x => x.TotalBill).NotNull();
                RuleFor(x => x.DiscountPercent).NotNull();
                RuleFor(x => x.DiscountAmount).NotNull();
                RuleFor(x => x.TaxAmount).NotNull();
                RuleFor(x => x.SoldBy).NotNull();
                RuleFor(x => x.ShopId).NotNull();
                RuleFor(x => x.DateSold).NotNull();
                RuleFor(x => x.TotalChange).NotNull();
                RuleFor(x => x.SaleTypeId).NotNull();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts Sale Dto to Sale EF Model
        /// </summary>
        /// <returns>Sale EF model</returns>
        public Sale ToEFModel()
        {
            var model = new Sale();
            model.SaleId = this.SaleId;
            model.TotalTendered = this.TotalTendered;
            model.TotalBill = this.TotalBill;
            model.DiscountPercent = this.DiscountPercent;
            model.DiscountAmount = this.DiscountAmount;
            model.TaxAmount = this.TaxAmount;
            model.SoldTo = this.SoldTo;
            model.SoldBy = this.SoldBy;
            model.ShopId = this.ShopId;
            model.DateSold = this.DateSold;
            model.TotalChange = this.TotalChange;
            model.SaleTypeId = this.SaleTypeId;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a Sale Entity Model
        /// </summary>
        /// <param name="model">Sale model</param>
        /// <returns>Sale Dto</returns>
        public static SaleDto FromEFModel(Sale model)
        {
            if(model == null) return null;
            var dto = new SaleDto();
            dto.SaleId = model.SaleId;
            dto.TotalTendered = model.TotalTendered;
            dto.TotalBill = model.TotalBill;
            dto.DiscountPercent = model.DiscountPercent;
            dto.DiscountAmount = model.DiscountAmount;
            dto.TaxAmount = model.TaxAmount;
            dto.SoldTo = model.SoldTo;
            dto.SoldBy = model.SoldBy;
            dto.ShopId = model.ShopId;
            dto.DateSold = model.DateSold;
            dto.TotalChange = model.TotalChange;
            dto.SaleTypeId = model.SaleTypeId;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int SaleId { get; set; }
        public double TotalTendered { get; set; }
        public double TotalBill { get; set; }
        public double DiscountPercent { get; set; }
        public double DiscountAmount { get; set; }
        public double TaxAmount { get; set; }
        public Nullable<int> SoldTo { get; set; }
        public int SoldBy { get; set; }
        public int ShopId { get; set; }
        public System.DateTime DateSold { get; set; }
        public double TotalChange { get; set; }
        public int SaleTypeId { get; set; }
        public int Deleted { get; set; }
    }
}
