//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class ShopDto
    {
        
        //Default Constructor
        public ShopDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<ShopDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.ShopId).NotNull();
                RuleFor(x => x.ShopName).MaximumLength(50);
                RuleFor(x => x.Location).MaximumLength(50);
                RuleFor(x => x.District).MaximumLength(50);
                RuleFor(x => x.Currency).MaximumLength(50);
                RuleFor(x => x.Deleted).NotNull();
                RuleFor(x => x.Country).MaximumLength(50);
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts Shop Dto to Shop EF Model
        /// </summary>
        /// <returns>Shop EF model</returns>
        public Shop ToEFModel()
        {
            var model = new Shop();
            model.ShopId = this.ShopId;
            model.ShopName = this.ShopName;
            model.Location = this.Location;
            model.District = this.District;
            model.CompanyId = this.CompanyId;
            model.Currency = this.Currency;
            model.Deleted = this.Deleted;
            model.Country = this.Country;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a Shop Entity Model
        /// </summary>
        /// <param name="model">Shop model</param>
        /// <returns>Shop Dto</returns>
        public static ShopDto FromEFModel(Shop model)
        {
            if(model == null) return null;
            var dto = new ShopDto();
            dto.ShopId = model.ShopId;
            dto.ShopName = model.ShopName;
            dto.Location = model.Location;
            dto.District = model.District;
            dto.CompanyId = model.CompanyId;
            dto.Currency = model.Currency;
            dto.Deleted = model.Deleted;
            dto.Country = model.Country;
            return dto;
        }
    
    
        public int ShopId { get; set; }
        public string ShopName { get; set; }
        public string Location { get; set; }
        public string District { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Currency { get; set; }
        public int Deleted { get; set; }
        public string Country { get; set; }
    }
}
