//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.ProductQuantities = new HashSet<ProductQuantity>();
        }
    
        public int ShopId { get; set; }
        public string ShopName { get; set; }
        public string Location { get; set; }
        public string District { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Currency { get; set; }
        public int Deleted { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductQuantity> ProductQuantities { get; set; }
        public virtual Setting Setting { get; set; }
    }
}
