//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class sysdiagramDto
    {
        
        //Default Constructor
        public sysdiagramDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<sysdiagramDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.name).MaximumLength(128).NotEmpty();
                RuleFor(x => x.principal_id).NotNull();
                RuleFor(x => x.diagram_id).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts sysdiagram Dto to sysdiagram EF Model
        /// </summary>
        /// <returns>sysdiagram EF model</returns>
        public sysdiagram ToEFModel()
        {
            var model = new sysdiagram();
            model.name = this.name;
            model.principal_id = this.principal_id;
            model.diagram_id = this.diagram_id;
            model.version = this.version;
            model.definition = this.definition;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a sysdiagram Entity Model
        /// </summary>
        /// <param name="model">sysdiagram model</param>
        /// <returns>sysdiagram Dto</returns>
        public static sysdiagramDto FromEFModel(sysdiagram model)
        {
            if(model == null) return null;
            var dto = new sysdiagramDto();
            dto.name = model.name;
            dto.principal_id = model.principal_id;
            dto.diagram_id = model.diagram_id;
            dto.version = model.version;
            dto.definition = model.definition;
            return dto;
        }
    
    
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
