//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class TaxTypeDto
    {
        
        //Default Constructor
        public TaxTypeDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<TaxTypeDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.TaxTypeId).NotNull();
                RuleFor(x => x.TaxTypeName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.TaxTypeValue).NotNull();
                RuleFor(x => x.TaxTypeStatus).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts TaxType Dto to TaxType EF Model
        /// </summary>
        /// <returns>TaxType EF model</returns>
        public TaxType ToEFModel()
        {
            var model = new TaxType();
            model.TaxTypeId = this.TaxTypeId;
            model.TaxTypeName = this.TaxTypeName;
            model.TaxTypeValue = this.TaxTypeValue;
            model.TaxTypeStatus = this.TaxTypeStatus;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a TaxType Entity Model
        /// </summary>
        /// <param name="model">TaxType model</param>
        /// <returns>TaxType Dto</returns>
        public static TaxTypeDto FromEFModel(TaxType model)
        {
            if(model == null) return null;
            var dto = new TaxTypeDto();
            dto.TaxTypeId = model.TaxTypeId;
            dto.TaxTypeName = model.TaxTypeName;
            dto.TaxTypeValue = model.TaxTypeValue;
            dto.TaxTypeStatus = model.TaxTypeStatus;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int TaxTypeId { get; set; }
        public string TaxTypeName { get; set; }
        public double TaxTypeValue { get; set; }
        public string TaxTypeStatus { get; set; }
        public int Deleted { get; set; }
    }
}
