//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxType
    {
        public int TaxTypeId { get; set; }
        public string TaxTypeName { get; set; }
        public double TaxTypeValue { get; set; }
        public string TaxTypeStatus { get; set; }
        public int Deleted { get; set; }
    }
}
