//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBrand
    {
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public int Deleted { get; set; }
        public string BrandDescription { get; set; }
        public string BrandTag { get; set; }
    }
}
