//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCart
    {
        public string ProductName { get; set; }
        public int UserId { get; set; }
        public int ShopId { get; set; }
        public double SellingPrice { get; set; }
        public double Qty { get; set; }
        public double DiscountAmount { get; set; }
        public double TaxValue { get; set; }
        public double TotalPrice { get; set; }
        public int CartId { get; set; }
        public int ProductId { get; set; }
    }
}
