//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwCartDto
    {
        
        //Default Constructor
        public vwCartDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwCartDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.ProductName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.UserId).NotNull();
                RuleFor(x => x.ShopId).NotNull();
                RuleFor(x => x.SellingPrice).NotNull();
                RuleFor(x => x.Qty).NotNull();
                RuleFor(x => x.DiscountAmount).NotNull();
                RuleFor(x => x.TaxValue).NotNull();
                RuleFor(x => x.TotalPrice).NotNull();
                RuleFor(x => x.CartId).NotNull();
                RuleFor(x => x.ProductId).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwCart Dto to vwCart EF Model
        /// </summary>
        /// <returns>vwCart EF model</returns>
        public vwCart ToEFModel()
        {
            var model = new vwCart();
            model.ProductName = this.ProductName;
            model.UserId = this.UserId;
            model.ShopId = this.ShopId;
            model.SellingPrice = this.SellingPrice;
            model.Qty = this.Qty;
            model.DiscountAmount = this.DiscountAmount;
            model.TaxValue = this.TaxValue;
            model.TotalPrice = this.TotalPrice;
            model.CartId = this.CartId;
            model.ProductId = this.ProductId;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwCart Entity Model
        /// </summary>
        /// <param name="model">vwCart model</param>
        /// <returns>vwCart Dto</returns>
        public static vwCartDto FromEFModel(vwCart model)
        {
            if(model == null) return null;
            var dto = new vwCartDto();
            dto.ProductName = model.ProductName;
            dto.UserId = model.UserId;
            dto.ShopId = model.ShopId;
            dto.SellingPrice = model.SellingPrice;
            dto.Qty = model.Qty;
            dto.DiscountAmount = model.DiscountAmount;
            dto.TaxValue = model.TaxValue;
            dto.TotalPrice = model.TotalPrice;
            dto.CartId = model.CartId;
            dto.ProductId = model.ProductId;
            return dto;
        }
    
    
        public string ProductName { get; set; }
        public int UserId { get; set; }
        public int ShopId { get; set; }
        public double SellingPrice { get; set; }
        public double Qty { get; set; }
        public double DiscountAmount { get; set; }
        public double TaxValue { get; set; }
        public double TotalPrice { get; set; }
        public int CartId { get; set; }
        public int ProductId { get; set; }
    }
}
