//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwCompanyDto
    {
        
        //Default Constructor
        public vwCompanyDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwCompanyDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.CompanyId).NotNull();
                RuleFor(x => x.Name).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Email).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Phone).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Ceo).MaximumLength(50).NotEmpty();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwCompany Dto to vwCompany EF Model
        /// </summary>
        /// <returns>vwCompany EF model</returns>
        public vwCompany ToEFModel()
        {
            var model = new vwCompany();
            model.CompanyId = this.CompanyId;
            model.Address = this.Address;
            model.Name = this.Name;
            model.Email = this.Email;
            model.Phone = this.Phone;
            model.Ceo = this.Ceo;
            model.Terms = this.Terms;
            model.Fee = this.Fee;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwCompany Entity Model
        /// </summary>
        /// <param name="model">vwCompany model</param>
        /// <returns>vwCompany Dto</returns>
        public static vwCompanyDto FromEFModel(vwCompany model)
        {
            if(model == null) return null;
            var dto = new vwCompanyDto();
            dto.CompanyId = model.CompanyId;
            dto.Address = model.Address;
            dto.Name = model.Name;
            dto.Email = model.Email;
            dto.Phone = model.Phone;
            dto.Ceo = model.Ceo;
            dto.Terms = model.Terms;
            dto.Fee = model.Fee;
            return dto;
        }
    
    
        public int CompanyId { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Ceo { get; set; }
        public string Terms { get; set; }
        public string Fee { get; set; }
    }
}
