//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwExpensDto
    {
        
        //Default Constructor
        public vwExpensDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwExpensDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.PaymentTypeName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Amount).NotNull();
                RuleFor(x => x.UserId).NotNull();
                RuleFor(x => x.Name).MaximumLength(50).NotEmpty();
                RuleFor(x => x.ExpenseDate).NotNull();
                RuleFor(x => x.AddedBy).NotNull();
                RuleFor(x => x.ExpenseId).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwExpens Dto to vwExpens EF Model
        /// </summary>
        /// <returns>vwExpens EF model</returns>
        public vwExpens ToEFModel()
        {
            var model = new vwExpens();
            model.ExpenseTypeName = this.ExpenseTypeName;
            model.PaymentTypeName = this.PaymentTypeName;
            model.Amount = this.Amount;
            model.UserId = this.UserId;
            model.Name = this.Name;
            model.ExpenseDate = this.ExpenseDate;
            model.AddedBy = this.AddedBy;
            model.ExpenseId = this.ExpenseId;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwExpens Entity Model
        /// </summary>
        /// <param name="model">vwExpens model</param>
        /// <returns>vwExpens Dto</returns>
        public static vwExpensDto FromEFModel(vwExpens model)
        {
            if(model == null) return null;
            var dto = new vwExpensDto();
            dto.ExpenseTypeName = model.ExpenseTypeName;
            dto.PaymentTypeName = model.PaymentTypeName;
            dto.Amount = model.Amount;
            dto.UserId = model.UserId;
            dto.Name = model.Name;
            dto.ExpenseDate = model.ExpenseDate;
            dto.AddedBy = model.AddedBy;
            dto.ExpenseId = model.ExpenseId;
            return dto;
        }
    
    
        public string ExpenseTypeName { get; set; }
        public string PaymentTypeName { get; set; }
        public double Amount { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public int AddedBy { get; set; }
        public int ExpenseId { get; set; }
    }
}
