//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwExpenseTypeDto
    {
        
        //Default Constructor
        public vwExpenseTypeDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwExpenseTypeDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.ExpenseTypeId).NotNull();
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwExpenseType Dto to vwExpenseType EF Model
        /// </summary>
        /// <returns>vwExpenseType EF model</returns>
        public vwExpenseType ToEFModel()
        {
            var model = new vwExpenseType();
            model.ExpenseTypeId = this.ExpenseTypeId;
            model.ExpenseTypeName = this.ExpenseTypeName;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwExpenseType Entity Model
        /// </summary>
        /// <param name="model">vwExpenseType model</param>
        /// <returns>vwExpenseType Dto</returns>
        public static vwExpenseTypeDto FromEFModel(vwExpenseType model)
        {
            if(model == null) return null;
            var dto = new vwExpenseTypeDto();
            dto.ExpenseTypeId = model.ExpenseTypeId;
            dto.ExpenseTypeName = model.ExpenseTypeName;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int ExpenseTypeId { get; set; }
        public string ExpenseTypeName { get; set; }
        public int Deleted { get; set; }
    }
}
