//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIncome
    {
        public string IncomeTypeName { get; set; }
        public decimal Amount { get; set; }
        public string PaymentTypeName { get; set; }
        public int IncomeId { get; set; }
        public int AddedBy { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public System.DateTime IncomeDate { get; set; }
    }
}
