//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwIncomeDto
    {
        
        //Default Constructor
        public vwIncomeDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwIncomeDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.Amount).NotNull();
                RuleFor(x => x.PaymentTypeName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.IncomeId).NotNull();
                RuleFor(x => x.AddedBy).NotNull();
                RuleFor(x => x.Name).MaximumLength(50).NotEmpty();
                RuleFor(x => x.UserId).NotNull();
                RuleFor(x => x.IncomeDate).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwIncome Dto to vwIncome EF Model
        /// </summary>
        /// <returns>vwIncome EF model</returns>
        public vwIncome ToEFModel()
        {
            var model = new vwIncome();
            model.IncomeTypeName = this.IncomeTypeName;
            model.Amount = this.Amount;
            model.PaymentTypeName = this.PaymentTypeName;
            model.IncomeId = this.IncomeId;
            model.AddedBy = this.AddedBy;
            model.Name = this.Name;
            model.UserId = this.UserId;
            model.IncomeDate = this.IncomeDate;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwIncome Entity Model
        /// </summary>
        /// <param name="model">vwIncome model</param>
        /// <returns>vwIncome Dto</returns>
        public static vwIncomeDto FromEFModel(vwIncome model)
        {
            if(model == null) return null;
            var dto = new vwIncomeDto();
            dto.IncomeTypeName = model.IncomeTypeName;
            dto.Amount = model.Amount;
            dto.PaymentTypeName = model.PaymentTypeName;
            dto.IncomeId = model.IncomeId;
            dto.AddedBy = model.AddedBy;
            dto.Name = model.Name;
            dto.UserId = model.UserId;
            dto.IncomeDate = model.IncomeDate;
            return dto;
        }
    
    
        public string IncomeTypeName { get; set; }
        public decimal Amount { get; set; }
        public string PaymentTypeName { get; set; }
        public int IncomeId { get; set; }
        public int AddedBy { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public System.DateTime IncomeDate { get; set; }
    }
}
