//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwRoleDto
    {
        
        //Default Constructor
        public vwRoleDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwRoleDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.RoleName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Deleted).NotNull();
                RuleFor(x => x.RoleId).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwRole Dto to vwRole EF Model
        /// </summary>
        /// <returns>vwRole EF model</returns>
        public vwRole ToEFModel()
        {
            var model = new vwRole();
            model.RoleName = this.RoleName;
            model.Deleted = this.Deleted;
            model.RoleId = this.RoleId;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwRole Entity Model
        /// </summary>
        /// <param name="model">vwRole model</param>
        /// <returns>vwRole Dto</returns>
        public static vwRoleDto FromEFModel(vwRole model)
        {
            if(model == null) return null;
            var dto = new vwRoleDto();
            dto.RoleName = model.RoleName;
            dto.Deleted = model.Deleted;
            dto.RoleId = model.RoleId;
            return dto;
        }
    
    
        public string RoleName { get; set; }
        public int Deleted { get; set; }
        public int RoleId { get; set; }
    }
}
