//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwShopDto
    {
        
        //Default Constructor
        public vwShopDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwShopDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.Currency).MaximumLength(50);
                RuleFor(x => x.ShopName).MaximumLength(50);
                RuleFor(x => x.ShopId).NotNull();
                RuleFor(x => x.Deleted).NotNull();
                RuleFor(x => x.Location).MaximumLength(50);
                RuleFor(x => x.District).MaximumLength(50);
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwShop Dto to vwShop EF Model
        /// </summary>
        /// <returns>vwShop EF model</returns>
        public vwShop ToEFModel()
        {
            var model = new vwShop();
            model.Currency = this.Currency;
            model.ShopName = this.ShopName;
            model.ShopId = this.ShopId;
            model.Deleted = this.Deleted;
            model.Location = this.Location;
            model.District = this.District;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwShop Entity Model
        /// </summary>
        /// <param name="model">vwShop model</param>
        /// <returns>vwShop Dto</returns>
        public static vwShopDto FromEFModel(vwShop model)
        {
            if(model == null) return null;
            var dto = new vwShopDto();
            dto.Currency = model.Currency;
            dto.ShopName = model.ShopName;
            dto.ShopId = model.ShopId;
            dto.Deleted = model.Deleted;
            dto.Location = model.Location;
            dto.District = model.District;
            return dto;
        }
    
    
        public string Currency { get; set; }
        public string ShopName { get; set; }
        public int ShopId { get; set; }
        public int Deleted { get; set; }
        public string Location { get; set; }
        public string District { get; set; }
    }
}
