//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwUnitDto
    {
        
        //Default Constructor
        public vwUnitDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwUnitDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.UnitId).NotNull();
                RuleFor(x => x.UnitName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.SubUnit).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Deleted).NotNull();
                RuleFor(x => x.UnitValue).NotNull();
                RuleFor(x => x.SubUnitValue).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwUnit Dto to vwUnit EF Model
        /// </summary>
        /// <returns>vwUnit EF model</returns>
        public vwUnit ToEFModel()
        {
            var model = new vwUnit();
            model.UnitId = this.UnitId;
            model.UnitName = this.UnitName;
            model.SubUnit = this.SubUnit;
            model.Deleted = this.Deleted;
            model.UnitValue = this.UnitValue;
            model.SubUnitValue = this.SubUnitValue;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwUnit Entity Model
        /// </summary>
        /// <param name="model">vwUnit model</param>
        /// <returns>vwUnit Dto</returns>
        public static vwUnitDto FromEFModel(vwUnit model)
        {
            if(model == null) return null;
            var dto = new vwUnitDto();
            dto.UnitId = model.UnitId;
            dto.UnitName = model.UnitName;
            dto.SubUnit = model.SubUnit;
            dto.Deleted = model.Deleted;
            dto.UnitValue = model.UnitValue;
            dto.SubUnitValue = model.SubUnitValue;
            return dto;
        }
    
    
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string SubUnit { get; set; }
        public int Deleted { get; set; }
        public double UnitValue { get; set; }
        public double SubUnitValue { get; set; }
    }
}
