//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUser
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string AltEmail { get; set; }
        public string Phone { get; set; }
        public string AltPhone { get; set; }
        public string PhysicalAddress { get; set; }
        public string ContactAddress { get; set; }
        public string RoleName { get; set; }
        public string ShopName { get; set; }
        public int Deleted { get; set; }
    }
}
