//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class vwUserDto
    {
        
        //Default Constructor
        public vwUserDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<vwUserDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.UserId).NotNull();
                RuleFor(x => x.Name).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Gender).MaximumLength(50).NotEmpty();
                RuleFor(x => x.UserName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Email).MaximumLength(50).NotEmpty();
                RuleFor(x => x.AltEmail).MaximumLength(50);
                RuleFor(x => x.Phone).MaximumLength(50).NotEmpty();
                RuleFor(x => x.AltPhone).MaximumLength(50);
                RuleFor(x => x.RoleName).MaximumLength(50).NotEmpty();
                RuleFor(x => x.ShopName).MaximumLength(50);
                RuleFor(x => x.Deleted).NotNull();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts vwUser Dto to vwUser EF Model
        /// </summary>
        /// <returns>vwUser EF model</returns>
        public vwUser ToEFModel()
        {
            var model = new vwUser();
            model.UserId = this.UserId;
            model.Name = this.Name;
            model.Gender = this.Gender;
            model.UserName = this.UserName;
            model.Email = this.Email;
            model.AltEmail = this.AltEmail;
            model.Phone = this.Phone;
            model.AltPhone = this.AltPhone;
            model.PhysicalAddress = this.PhysicalAddress;
            model.ContactAddress = this.ContactAddress;
            model.RoleName = this.RoleName;
            model.ShopName = this.ShopName;
            model.Deleted = this.Deleted;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a vwUser Entity Model
        /// </summary>
        /// <param name="model">vwUser model</param>
        /// <returns>vwUser Dto</returns>
        public static vwUserDto FromEFModel(vwUser model)
        {
            if(model == null) return null;
            var dto = new vwUserDto();
            dto.UserId = model.UserId;
            dto.Name = model.Name;
            dto.Gender = model.Gender;
            dto.UserName = model.UserName;
            dto.Email = model.Email;
            dto.AltEmail = model.AltEmail;
            dto.Phone = model.Phone;
            dto.AltPhone = model.AltPhone;
            dto.PhysicalAddress = model.PhysicalAddress;
            dto.ContactAddress = model.ContactAddress;
            dto.RoleName = model.RoleName;
            dto.ShopName = model.ShopName;
            dto.Deleted = model.Deleted;
            return dto;
        }
    
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string AltEmail { get; set; }
        public string Phone { get; set; }
        public string AltPhone { get; set; }
        public string PhysicalAddress { get; set; }
        public string ContactAddress { get; set; }
        public string RoleName { get; set; }
        public string ShopName { get; set; }
        public int Deleted { get; set; }
    }
}
